###
GET http://localhost:8080/ds_testing_system_sakura_update_war_exploded/do?command=getAvailableTestList

###
POST http://localhost:8080/ds_testing_system_sakura_update_war_exploded/do
Content-Type: application/json

{"command": "login", "login": "admin", "pass": "AdminPassword2023"}

###
POST http://localhost:8080/ds_testing_system_sakura_update_war_exploded/do
Content-Type: application/json

{"command": "getAvailableTestList"}

